# Build settings
markdown:           kramdown
permalink:          pretty


# Dependencies

markdown:           kramdown
highlighter:        rouge
gems:               [plug-ins]

# Permalinks
permalink:          pretty

# Setup
title:              "Technical Writing"
tagline:
description:        "E235|Pierce College|W20"
host:               127.0.0.1
url:                ""
baseurl:            "/235v2"
email:              jloan@pierce.ctc.edu


paginate:           5
layout:             blog-post

# Custom vars
version:            2.0.0

